apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: kruui1r6h-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/kruui1r6h-java-springboot-gitops