apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kruui1r6h-java-springboot
  janus-idp.io/tekton: kruui1r6h-java-springboot
  backstage.io/kubernetes-id: kruui1r6h-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kruui1r6h-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
